[package]
name = "sctk-simple-window"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay-client-toolkit = "0.19.2"
wayland-client = { version = "0.31.5", features = ["log"] }
env_logger = "0.11.5"
rand = "0.8.5"
